# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "dae515a686de7cf17d0bdd5b09ca5a26"
application_url = "https://flashbar-eta.vercel.app"
embedded = true
name = "FlashBar"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [
  "https://flashbar-eta.vercel.app/auth/callback"
]
